### ISSUE TITLE
Crashes while processing .fits file

### ISSUE THREAD

**Issue by JPVentura135** [BU-hammerTeam/PyHammer#5]
While attempting to process one spectrum, I got some errors which are pasted below:

1) Processing spec-0473-51929-0157.fits
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/JPeg/anaconda/envs/solarium3.5/lib/python3.5/site-packages/matplotlib/backends/tkagg.py", line 22, in blit
    id(data), colormode, id(bbox_array))
_tkinter.TclError: invalid command name "PyAggImagePhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/JPeg/anaconda/envs/solarium3.5/lib/python3.5/tkinter/__init__.py", line 1550, in __call__
    return self.func(*args)
  File "/Users/JPeg/anaconda/envs/solarium3.5/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 283, in resize
    self.show()
  File "/Users/JPeg/anaconda/envs/solarium3.5/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 355, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/Users/JPeg/anaconda/envs/solarium3.5/lib/python3.5/site-packages/matplotlib/backends/tkagg.py", line 30, in blit
    id(data), colormode, id(bbox_array))
_tkinter.TclError
python(1800,0x7fff766df000) malloc: *** error for object 0x1029b4d90: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by zephyr5050** [comment]
We cannot reproduce the issue by running on the same spectrum. Can you post your current operating system (and version), python version, matplotlib version, and tkinter version?

**Comment by JPVentura135** [comment]
Hello, 

I'm using Mac OS X 10.11.5,  Python 3.5.2 :: Anaconda 4.1.1 (x86_64) , Matplotlib 1.5.1, tk 8.5.18

However, i was able to fix my issues by changing "TkAgg" in eyecheck.py to "Qt4Agg".

**Comment by zephyr5050** [comment]
We previously used the TkAgg backend by default for Macs as that appeared to work for every case we tried. It seems your particular setup doesn't work. We're going to try switching to the Qt4Agg backend for macs by default. Please let us know if this causes any further problems.
